---
title: "Depression"
author: "Ifrah Fayyaz"
date: "2/14/2022"
output: html_document
---

<!-- big picture of the class of drugs - is depression important -->
<!-- take them under focus - total cost for people who took mental health services -->
<!-- 15% paid by employee, 85% by employer -->

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(sqldf)
library(plotly)
library(ggrepel)
library(stringr)
library(cowplot)

med_2020 = read_xlsx("Medical 2020.xlsx") %>%
  janitor::clean_names()
rx_2020 = read_xlsx("Rx 2020.xlsx") %>%
  janitor::clean_names()
hris = read_xlsx("HRIS.xlsx") %>%
  janitor::clean_names()
risk = read_xlsx("Risk 2020.xlsx") %>%
  janitor::clean_names()
hosp = read_xlsx("hospital 2020.xlsx") %>%
  janitor::clean_names()
```


## ICD-10 filtering (ALL)
```{r}
all_depressed = med_2020 %>%
  group_by(person, from, to) %>% 
  mutate(sum_cost = sum(cost)) %>% 
  filter(sum_cost > 0) %>% 
  ungroup() %>%
  filter(str_detect(icd10, "^F")) %>%
  filter(!str_detect(icd10, "^F7"))
```


## ICD-10 filtering
```{r}
depression = med_2020 %>% 
  mutate(keep = ifelse((str_detect(icd10, paste(c("^F32", "^F33", "F03.90", "F34.1", "F43.21", "F06.31", "F06.32", "F25.1", "^F41", "R45.851"), collapse = "|"))),1,
                       ifelse((str_detect(cpt4, paste(c(as.character(99201:99205, 99211:99215, 90791, 90792, 90834, 90837, 90847)), collapse = "|"))),1,0))) %>%
  filter(keep == 1) %>%
  group_by(person, from, to) %>%
  mutate(total_cost = sum(cost)) %>% 
  filter(total_cost > 0) %>%
  distinct(person, from, to, .keep_all = TRUE) %>% 
  ungroup()
```

## Unique people
```{r}
people = sqldf("SELECT DISTINCT(person), gender, age_range
               FROM depression")
```

## ER Visit
```{r}
er_visits = depression %>%
  filter(er == 1)
```

## Gender
```{r}
sqldf("SELECT COUNT(person), gender
      FROM people
      GROUP BY gender")
```

## Age Range
```{r}
sqldf("SELECT COUNT(person), age_range
      FROM people
      GROUP BY age_range")
```

## POS
```{r}
sqldf("SELECT COUNT(person), pos
      FROM depression
      GROUP BY pos")
```

## PCP Visit
```{r}
sqldf("SELECT COUNT(person), pcp
      FROM depression
      WHERE pcp == 'Y'
      GROUP BY pcp")
```

## Length of stay
```{r}
los = depression %>%
  mutate(duration = to - from)
```

## Summary Statistics
```{r}
table(los$age_range, los$pos)
```

## RX
```{r}
supply = sqldf("SELECT DISTINCT person, SUM(days) AS supply, class
       FROM rx_2020
       WHERE class IN ('ANTIANXIETY AGENTS', 'ANTIDEPRESSANTS') AND Units > 0
       GROUP BY person, class")
```

## Merge (drugs and med)
```{r}
both = depression %>%
  inner_join(supply, by = "person") %>%
  distinct(person, .keep_all = T)
```

## Merge (all people)
```{r}
all_people = depression %>%
  full_join(supply, by = "person") %>%
  distinct(person, .keep_all = T)
```

## Pie for people on depression meds
```{r}
meds = sqldf("SELECT COUNT(DISTINCT(person)) AS total_people, class
       FROM rx_2020
       GROUP BY class")
  
  
dep_med = sqldf("SELECT total_people, class
       FROM meds
       ORDER BY total_people DESC
       LIMIT 5") 

others = sqldf("SELECT total_people, class
       FROM meds
       ORDER BY total_people
       LIMIT 74") 

anxiety_ppl = sqldf("SELECT total_people, class
       FROM meds
       WHERE class == 'ANTIANXIETY AGENTS'")

others = sqldf("SELECT SUM(total_people) AS total_people
        FROM others") %>%
  mutate(class = "OTHERS")

others = others %>%
  mutate(total_people = total_people - 118)

pie_med = rbind(dep_med, anxiety_ppl, others) %>%
  mutate(perc = `total_people` / sum(`total_people`)) %>% 
  mutate(labels = scales::percent(perc)) %>%
  mutate(class = str_to_title(class))


df2 <- pie_med %>% 
  mutate(csum = rev(cumsum(rev(perc*100))), 
         pos = (perc*100)/2 + lead(csum, 1),
         pos = if_else(is.na(pos), (perc*100)/2, pos))

#dep_ppl_pie = 
  
  ggplot(pie_med, aes(x = "" , y = perc*100, fill = fct_inorder(class))) +
  geom_col(width = 1, color = 1) +
  coord_polar(theta = "y") +
  scale_fill_brewer(palette = "Pastel1") +
  geom_label_repel(data = df2, aes(y = pos, label = labels),
                   size = 3.5, nudge_x = 1.1, show.legend = FALSE) +
  guides(fill = guide_legend(title = "Class")) +
  theme_void() +
  ggtitle("Breakdown of different medications by individuals")

```

## Supply of drugs
```{r, message=FALSE, warning=FALSE, dpi=300}
supply = sqldf("SELECT class, SUM(Days) AS supply
       FROM rx_2020
       GROUP BY class
       HAVING supply > 0")

dep_supply = sqldf("SELECT supply, class
       FROM supply
       ORDER BY supply DESC
       LIMIT 5") 

anxiety = sqldf("SELECT supply, class
       FROM supply
       WHERE class == 'ANTIANXIETY AGENTS'")

other_supply = sqldf("SELECT supply, class
       FROM supply
       ORDER BY supply
       LIMIT 73") 

other_supply = sqldf("SELECT SUM(supply) AS supply
        FROM other_supply") %>%
  mutate(class = "OTHERS")

other_supply = other_supply %>%
  mutate(supply = supply - 10093)

med_supply = rbind(dep_supply, anxiety, other_supply) %>%
  mutate(perc = `supply` / sum(`supply`)) %>% 
  mutate(labels = scales::percent(perc)) %>%
  mutate(class = str_to_title(class))

df2 <- med_supply %>% 
  mutate(csum = rev(cumsum(rev(perc*100))), 
         pos = (perc*100)/2 + lead(csum, 1),
         pos = if_else(is.na(pos), (perc*100)/2, pos))

#dep_med_pie = 
  
  ggplot(med_supply, aes(x = "" , y = perc*100, fill = fct_inorder(class))) +
  geom_col(width = 1, color = 1) +
  coord_polar(theta = "y") +
  scale_fill_brewer(palette = "Pastel1") +
  geom_label_repel(data = df2, aes(y = pos, label = labels),
                   size = 3.5, nudge_x = 1.1, show.legend = FALSE) +
  guides(fill = guide_legend(title = "Class")) +
  theme_void() +
  ggtitle("Breakdown of different medications by supply")

#plot_grid(dep_ppl_pie, dep_med_pie, nrow = 1)
```


## Price of medications
```{r, message=FALSE, warning=FALSE, dpi=300}
cost = sqldf("SELECT class, SUM(cost) AS cost
       FROM rx_2020
       GROUP BY class
       HAVING cost > 0")

dep_cost = sqldf("SELECT cost, class
       FROM cost
       ORDER BY cost DESC
       LIMIT 6") 

anxiety_cost = sqldf("SELECT cost, class
       FROM cost
       WHERE class == 'ANTIANXIETY AGENTS'")

other_cost = sqldf("SELECT cost, class
       FROM cost
       ORDER BY cost
       LIMIT 72") 

other_cost = sqldf("SELECT SUM(cost) AS cost
        FROM other_cost") %>%
  mutate(class = "OTHERS")

other_cost = other_cost %>%
  mutate(cost = cost - 10093)

med_cost = rbind(dep_cost, anxiety_cost, other_cost) %>%
  mutate(perc = `cost` / sum(`cost`)) %>% 
  mutate(labels = scales::percent(perc)) %>%
  mutate(class = str_to_title(class))

df2 <- med_cost %>% 
  mutate(csum = rev(cumsum(rev(perc*100))), 
         pos = (perc*100)/2 + lead(csum, 1),
         pos = if_else(is.na(pos), (perc*100)/2, pos))

#dep_med_pie = 
  
  ggplot(med_cost, aes(x = "" , y = perc*100, fill = fct_inorder(class))) +
  geom_col(width = 1, color = 1) +
  coord_polar(theta = "y") +
  scale_fill_brewer(palette = "Pastel1") +
  geom_label_repel(data = df2, aes(y = pos, label = labels),
                   size = 3.5, nudge_x = 1.1, show.legend = FALSE) +
  guides(fill = guide_legend(title = "Class")) +
  theme_void() +
  ggtitle("Breakdown of different medications by cost")

#plot_grid(dep_ppl_pie, dep_med_pie, nrow = 1)
```

## Nurses and non-Nurses
```{r, message=FALSE, warning=FALSE}
all_depressed = 
all_depressed %>% 
  mutate(illness = ifelse(grepl("F0", icd10), "Mental disorders due to known physiological conditions",
                ifelse(grepl("F1", icd10), "Mental and behavioral disorders due to psychoactive subtance use",
                ifelse(grepl("F2", icd10), "Schizophrenia, schizotypal, delusional and other mood disorders",
                ifelse(grepl("F3", icd10), "Mood (affective) disorders",
                ifelse(grepl("F4", icd10), "Anxiety, dissociative, stress-related, somatoform, and other nonpsychotic mental disorders",
                ifelse(grepl("F5", icd10), "Behavioral syndromes associated with physiological disturbances and physical factors",
                ifelse(grepl("F6", icd10), "Disorders of adult personality and behavior",
                ifelse(grepl("F8", icd10), "Pervasive and specific developmental disorders",
                ifelse(grepl("F9", icd10), "Behavioral and emotional disorders with onset usually occurring in childhood and adolescence", "NA"))))))))))

all_depressed = all_depressed %>%
  #filter(illness == "Mood (affective) disorders") %>%
  distinct(person, .keep_all = T)

check_nurses = all_depressed %>%
  inner_join(hris, by = "person")

sqldf("SELECT nurse, COUNT()
       FROM check_nurses
       GROUP BY nurse")


check_nurses = rx_2020 %>%
  filter(class == 'ANTIDEPRESSANTS') %>%
  inner_join(hris, by = "person") %>%
  distinct(person, .keep_all = T)

a = sqldf("SELECT nurse, class, COUNT() AS number
       FROM check_nurses
       GROUP BY nurse, class")

check_nurses = rx_2020 %>%
  filter(class == 'ANTIDEPRESSANTS') %>%
  distinct(person, .keep_all = T)

a = sqldf("SELECT rel_code, class, COUNT() AS number
       FROM check_nurses
       GROUP BY rel_code, class")

dep_emp = rx_2020 %>%
  filter(class == 'ANTIDEPRESSANTS') %>%
  filter(rel_code == "E") %>%
  inner_join(hris, by = "person") %>%
  distinct(person, .keep_all = T)

a = sqldf("SELECT nurse, COUNT() as number
       FROM dep_emp
       GROUP BY nurse")


nurse_meds = rx_2020 %>%
  inner_join(hris, by = "person") %>%
  distinct(person, .keep_all = T)

a = sqldf("SELECT nurse, COUNT() as number
       FROM nurse_meds
       GROUP BY nurse")


dep_hosp = all_depressed %>%
  inner_join(hosp, by = "person") %>%
  distinct(person, .keep_all = T)
```

## People not diagnosed with depression but on anti-depression medication:
```{r}
hallway = sqldf("SELECT person, days 
                 FROM check_nurses 
                 WHERE Person NOT IN
                 (SELECT Person
                  FROM all_depressed)")

hallway = hallway %>%
  inner_join(med_2020, by = "person") %>%
  distinct(person, .keep_all = T)


sqldf("SELECT COUNT(icd10) AS freq, icd10
      FROM hallway
      GROUP BY icd10
      ORDER BY freq DESC")

sqldf("SELECT COUNT(DISTINCT(person)), rel_code
      FROM rx_2020
      GROUP BY rel_code")
```

```{r}
cancer = med_2020 %>%
  group_by(person, from, to) %>% 
  mutate(sum_cost = sum(cost)) %>% 
  filter(sum_cost > 0) %>% 
  ungroup() %>%
  filter(str_detect(icd10, c("^C", "Z12.31", "Z12.4"))) %>%
  filter(!str_detect(icd10, "^C3"))

can_dep = check_nurses %>%
  inner_join(cancer, by = "person") %>%
  distinct(person, .keep_all = T)
```

```{r}
dep = sqldf("SELECT Person, SUM(Days) AS supply
       FROM rx_2020
       WHERE class == 'ANTIDEPRESSANTS'
       GROUP BY Person
       HAVING supply >= 180")

dep = dep %>%
  inner_join(rx_2020, by = "person") %>%
  distinct(person, .keep_all = T)

sqldf("SELECT COUNT(Person) AS freq, relcode
       FROM all_depressed
       GROUP BY relcode")

sqldf("SELECT COUNT(Person) AS freq, gender
       FROM dep
       GROUP BY gender")
```

```{r}
med = med_2020 %>%
  group_by(person, from, to) %>% 
  mutate(sum_cost = sum(cost)) %>% 
  filter(sum_cost > 0) %>% 
  distinct(person, from, .keep_all = T)

visits = sqldf("SELECT person, `from` 
                 FROM med 
                 WHERE person IN
                 (SELECT person
                  FROM all_depressed)")

visits = sqldf("SELECT COUNT(person) AS visit, person
                 FROM visits 
                 GROUP BY person")

a = sqldf("SELECT DISTINCT person, `from` 
         FROM med 
         WHERE relcode == 'E'")

visits = visits %>%
  inner_join(rx_2020, by = "person") %>%
  distinct(person, .keep_all = T)

sqldf("SELECT SUM(visit) AS visit, rel_code
       FROM visits 
       GROUP BY rel_code")
```


```{r}
chronic = dep %>%
  inner_join(rx_2020, by = "person") %>%
  janitor::clean_names() 

sqldf("SELECT COUNT(DISTINCT(person)) AS people, class_x
       FROM chronic 
       GROUP BY class_x
       ORDER BY people")


chronic = sqldf("SELECT Person, class, SUM(Days) AS supply
       FROM rx_2020
       GROUP BY Person
       HAVING supply >= 180")

chronic = chronic %>%
  filter(class == "ANTIDEPRESSANTS")
```


```{r}
abc = risk  %>%
  inner_join(rx_2020, by = "person") %>%
  filter(class == "ANTIDEPRESSANTS") %>%
  mutate(diabetes = ifelse(diabetes == "Y", 1, 0)) %>%
  mutate(lung = ifelse(lung == "Y", 1, 0)) %>%
  mutate(heart = ifelse(heart == "Y", 1, 0)) %>%
  mutate(hyper = ifelse(hyper == "Y", 1, 0)) %>%
  mutate(cancer = ifelse(cancer == "Y", 1, 0)) %>%
  mutate(lipid = ifelse(lipid == "Y", 1, 0)) %>%
  filter(rel_code.x == "E")

sqldf("SELECT COUNT(DISTINCT(person))
      FROM abc
      WHERE heart == 1")

# disease   All   E     Total
# diabetes  35    23    50
# lung      7     4     11   
# hyper     102   74    207
# cancer    1     1     5
# lipid     117   93    280
# heart     26    17    32
```



